name: diffae
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  #- python=3.9
  - pytorch=1.8.1
  - torchvision>=0.9.1
  - cudatoolkit=11.1  # or the version matching your CUDA installation
  - pytorch-lightning>=1.4.5
  - torchmetrics>=0.5.0
  - scipy>=1.5.4
  - numpy>=1.19.5
  - tqdm
  - pandas>=1.1.5
  - python-lmdb>=1.2.1
  - ftfy
  - regex
  - matplotlib
  - imageio
  - imageio-ffmpeg
  - pip
  - pip:
    - pytorch-fid==0.3.0
    - lpips>=0.1.4
    - Pillow